export const REQUEST_MATRIX = "REQUEST_MATRIX";
export const RECEIVE_MATRIX = "RECEIVE_MATRIX";
export const RECEIVE_MATRIX_ERROR = "RECEIVE_MATRIX_ERROR";
export const REQUEST_VALIDATE = "REQUEST_VALIDATE";
export const RECEIVE_VALIDATE = "RECEIVE_VALIDATE";
export const RECEIVE_VALIDATE_ERROR = "RECEIVE_VALIDATE_ERROR";
